; DIY ESP32-C3 Super Mini with E22P-868M30S and Dot-Matrix display (MAX7219)

[diy_esp32c3_dot_matrix]
extends = esp32_base
board = esp32-c3-devkitm-1
build_flags =
  ${esp32_base.build_flags}
  -I variants/diy_esp32c3_dot_matrix
  -D ESP32_CPU_FREQ=80
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D P_LORA_DIO_1=2
  -D P_LORA_NSS=7
  -D P_LORA_RESET=3
  -D P_LORA_BUSY=10
  -D P_LORA_SCLK=4
  -D P_LORA_MISO=5
  -D P_LORA_MOSI=6
  -D P_LORA_TX_LED=8
  -D PIN_VBAT_READ=0
  -D SX126X_DIO2_AS_RF_SWITCH=true
  -D SX126X_DIO3_TCXO_VOLTAGE=1.8
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_RX_BOOSTED_GAIN=1
  -D LORA_TX_POWER=22
build_src_filter = ${esp32_base.build_src_filter}
  +<../variants/diy_esp32c3_dot_matrix>
lib_deps =
  ${esp32_base.lib_deps}

[env:diy_esp32c3_dot_matrix_companion_ble_fwd]
extends = diy_esp32c3_dot_matrix
build_flags =
  ${diy_esp32c3_dot_matrix.build_flags}
  -D MAX_CONTACTS=200
  -D MAX_GROUP_CHANNELS=16
  -D BLE_PIN_CODE=123456
  -D ADVERT_NAME='"DotMatrix-LoRa"'
  -D WITH_SERIAL_FORWARD=Serial1
  -D WITH_SERIAL_FORWARD_TX=21
  -D WITH_SERIAL_FORWARD_RX=20
  -D WITH_SERIAL_FORWARD_DM=1
; NOTE: DO NOT ENABLE -->  -D MESH_PACKET_LOGGING=1
; NOTE: DO NOT ENABLE -->  -D MESH_DEBUG=1
build_src_filter = ${diy_esp32c3_dot_matrix.build_src_filter}
  +<../examples/companion_radio/*.cpp>
  +<helpers/esp32/*.cpp>
  +<helpers/SerialForward.cpp>
lib_deps =
  ${diy_esp32c3_dot_matrix.lib_deps}
  densaugeo/base64 @ ~1.4.0
